<?php

define('CARD_TYPE_STOREFRONT', "CARD_TYPE_STOREFRONT");
define('CARD_TYPE_PRODUCT', "CARD_TYPE_PRODUCT");

define('FETCH_MARKETPLACE', "FETCH_MARKETPLACE");
define('FETCH_FEATURE_STOREFRONTS', "FETCH_FEATURE_STOREFRONTS");
define('FETCH_STOREFRONT', "FETCH_STOREFRONT");
define('FETCH_STOREFRONT_SHARE', "FETCH_STOREFRONT_SHARE");
define('FETCH_PRODUCTS_FOR_STOREFRONT', "FETCH_PRODUCTS_FOR_STOREFRONT");
define('FETCH_PRODUCT', "FETCH_PRODUCT");
define('FETCH_FLIP_CLAIM', "FETCH_FLIP_CLAIM");
define('VALIDATE_PRODUCT', "VALIDATE_PRODUCT");

define('SUBSCRIBE_TO_STOREFRONT', "SUBSCRIBE_TO_STOREFRONT");
define('SUBSCRIBE_TO_PRODUCT', "SUBSCRIBE_TO_PRODUCT");

define('UPDATE_PRODUCT_TYPE', "UPDATE_PRODUCT_TYPE");


/*
define('', "");
define('', "");
define('', "");
define('', "");
define('', "");
define('', "");
define('', "");
define('', "");*/
?>